version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  gateway:
    build: gateway/
    ports:
      - "8083:8083"
  authserver:
    build: authserver/
    ports:
      - "9999:9999"
  resource:
    build: resource/
  ui:
    build: ui/
  admin:
    build: admin/