server:
  port: 8083
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
security:
  sessions: ALWAYS
spring:
  session:
    store-type: redis