server:
  port: 8081
spring:
  session:
    store-type: redis
security:
  user:
    password: password
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers: